bookings/urls.py
from django.conf.urls import url

from  .views import  get_home, get_booking_system
urlpatterns = [

    url(r'^$', get_home, name='home'),
    url(r'^booking/(?P<session_id>\d+)/$', get_booking_system, name='book')
]

calander_booking/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from settings import STATIC_ROOT, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Static
    url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    # Media Root
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    url(r'', include('bookings.urls'))
]

bookings/models.py
from django.db import models
from django.core.exceptions import ValidationError
from datetime import time

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    image = models.ImageField(upload_to='images')
    description = models.TextField()
    slots = models.IntegerField()

    def __unicode__(self):
        return self.name

class Booking(models.Model):

    TIME_CHOICES = (
        (time(11, 00, 00), u'11 AM'),
        (time(12, 00, 00), u'12 PM'),
        (time(13, 00, 00), u'1 PM'),
        (time(14, 00, 00), u'2 PM'),
        (time(15, 00, 00), u'3 PM'),
        (time(16, 00, 00), u'4 PM'),
        (time(17, 00, 00), u'5 PM'),
    )


    day = models.DateField(u'Booking date')


    start_time = models.TimeField(u'Booking time', choices=TIME_CHOICES, max_length=200)
    notes = models.CharField(u'Notes', blank=True, null=True, max_length=500)

    type_class = models.ForeignKey(Product)

    stripe_id = models.CharField(max_length=40, default='')

    class Meta:
        verbose_name = 'Booking'
        verbose_name_plural = 'Booking'

    def __unicode__(self):
        return str(self.day) + ' - ' + str(self.start_time)


    def check_availability(self, taken_slots, max_slots):

        full = False

        if taken_slots >= max_slots:
            full = True

        return full


    def clean(self):

        events = Booking.objects.filter(day=self.day, start_time=self.start_time, type_class=self.type_class).count()

        if events:
            if self.check_availability(events, self.type_class.slots):
                raise ValidationError('Too many bookings')

bookings/forms.py
from django import forms
from .models import Booking,Product


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('day', 'start_time', 'notes', 'type_class', 'stripe_id')

    day = forms.DateField(
        widget=forms.widgets.DateInput(format="%m/%d/%Y"))

    MONTHS = [
        'Jan', 'Feb', 'Mar', 'Apr', 'May', 'June',
        'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'
    ]

    MONTH_CHOICES = list(enumerate(MONTHS, 1))
    YEAR_CHOICES = [(i, i) for i in range(2016, 2027)]

    credit_card_number = forms.CharField(label='Credit card number')
    cvv = forms.CharField(label='CVV')
    expiry_month = forms.ChoiceField(choices=MONTH_CHOICES)
    expiry_year = forms.ChoiceField(choices=YEAR_CHOICES)

    stripe_id = forms.CharField(widget=forms.HiddenInput)

bookings/views.py
from django.shortcuts import render, redirect,reverse
from django.contrib import messages


from django.template.context_processors import csrf
import stripe
import stripe.error

import datetime

from django.conf import settings
from .forms import BookingForm
from .models import Product


# Create your views here.

def get_home(request):
    session = Product.objects.all()
    args = {'session': session}
    return render(request, 'home.html', args)


def get_booking_system(request, session_id):

    session_name = Product.objects.get(id=session_id)
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            try:
                charge = int(session_name.price * 100)
                customer = stripe.Charge.create(
                    amount= charge,
                    currency="GBP",
                    description=form.cleaned_data['type_class'],
                    card=form.cleaned_data['stripe_id'],
                )
                if customer.paid:
                    new_form = form.save(False)
                    new_form.type_class = form.cleaned_data['type_class']
                    new_form.save()
                else:
                    messages.error(request, "We were unable to take a payment with that card!")
            except stripe.error.CardError, e:
                messages.error(request, "Your card was declined!")

            messages.success(request, 'Thank you for your booking!')
            return redirect('home')
    else:
        form = BookingForm()
    args = {'form': form, 'session_id': session_id, 'session_name':session_name, 'publishable': settings.STRIPE_PUBLISHABLE}
    args.update(csrf(request))
    return render(request, 'booking.html', args)

templates/booking.html
{% extends 'index.html' %}
{% load bootstrap_tags %}
{% load custom_tags %}
{% load static %}


{% block head_js %}
  <script src="https://js.stripe.com/v2/" type="text/javascript"></script>
  <script type="text/javascript">
      //<![CDATA[
      Stripe.publishableKey = '{{ publishable }}';
      //]]>
  </script>
  <script type="text/javascript" src="{% static 'js/stripe.js' %}"></script>

{% endblock %}



{% block content %}

    <h1>{{ session_name.name }}</h1>
    <h3>£{{ session_name.price }}</h3>
    <form method="POST" id="booking-form">

    <div class="row">
        {% csrf_token %}
        {{ form|as_bootstrap }}

        <div id="credit-card-errors" style="display:none">
            <div class="alert-message block-message error" id="stripe-error-message"></div></div>
            <div class="form-group">
                <input class="btn btn-primary" id="validate_card_btn" name="commit" type="submit" value="Validate Credit Card">
            </div>
        </div>
    </form>



    <script type="text/javascript">
    $(window).ready(function(){
        $('#id_type_class option').attr('selected', 'selected');
        $("#div_id_day").addClass('wrap-1');
        $("#div_id_start_time").addClass('wrap-1');
        $("#div_id_notes").addClass('wrap-1');
        $("#div_id_type_class").addClass('wrap-1').hide();

        $('.wrap-1').wrapAll("<div class='col-md-6'>");



        $("#div_id_credit_card_number").addClass('wrap-2');
        $("#div_id_cvv").addClass('wrap-2');
        $("#div_id_expiry_month").addClass('wrap-2');
        $("#div_id_expiry_year").addClass('wrap-2');


        $('.wrap-2').wrapAll("<div class='col-md-6'>");
    });

    $(window).beforeunload(function () {
        $('#id_type_class option').attr('selected', 'selected');
    })

    </script>
{% endblock %}

templates/home.html
{% extends 'index.html' %}


{% block content %}

    <div class="my-row">
        {% for sesh in session %}
            {% include 'session_card.html' %}
        {% endfor %}
    </div>
{% endblock %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

     <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="/static/stlye/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <title>Booking</title>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script type="text/javascript" src="/static/js/jquery.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    {% block head_js %}{% endblock %}
 </head>


<body>
    <div class="my-container">
        <div class="jumbotron">
            <h1>Calendar Booking System</h1>
            <h2 class=card-footer">Book a Class</h2>
        </div>

        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}




        {% block content %}

        {% endblock %}
    </div>

    <script>
    $( function() {
        $( "#id_day" ).datepicker({
            beforeShowDay: function(date) {
                var day = date.getDay();
                return [(day != 0), ''];
        }
        });
    });
    </script>
</body>

</html>

templates/session_card.html
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{ sesh.image.url }}" alt="Card image cap">
  <div class="card-body">
        <h5 class="card-title">{{ sesh.name }}</h5>
        <h6 class="card-text">£{{ sesh.price }}</h6>
        <p class="card-text">{{ sesh.description|truncatewords:22 }}</p>
        <a class="btn btn-primary" href="/booking/{{ sesh.id }}">Book a Slot!</a>
    </div>
</div>